export { default as CreateBlobPage } from './CreateBlob';
export { default as CreateDocumentPage } from './CreateDocument';
export { default as DeleteBlobPage } from './DeleteBlob';
export { default as DeleteDocumentPage } from './DeleteDocument';
export { default as GetBlobPage } from './GetBlob';
export { default as UpdateDocumnetPage } from './UpdateDocument';
export { default as GetDocumnetPage } from './GetDocument';
export { default as ChangeDocumnetPage } from './ChangeDocument';
export { default as CreateBatchPage } from './CreateBatch';